"use client";

import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { Inter } from "next/font/google";

// Use Inter font for a modern look
const inter = Inter({ subsets: ["latin"] });

// --- TYPESCRIPT FIX: Define proper interface ---
interface NavLinkProps {
  href: string;
  active: boolean;
  label: string;
  icon: React.ReactNode;
  extraIcon?: React.ReactNode;
}

export default function ClientLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname() || "/";
  const hideNavbar = pathname.startsWith("/auth");

  const isActive = (p: string) => pathname === p || pathname.startsWith(p + "/");

  // UI-only: remove "Latest posts" headings if generated by Next.js templates
  useEffect(() => {
    if (typeof window === "undefined") return;
    const candidates = Array.from(document.querySelectorAll("h1,h2,h3,p,div,span"));
    candidates.forEach((el) => {
      try {
        if (el.textContent?.trim() === "Latest posts") el.remove();
      } catch {
        /* noop */
      }
    });
  }, []);

  return (
    <div className={`min-h-screen bg-zinc-50 ${inter.className}`}>
      
      {/* --- MOBILE TOP HEADER --- */}
      {!hideNavbar && (
        <header className="fixed top-0 left-0 right-0 z-50 md:hidden bg-white/80 backdrop-blur-md border-b border-zinc-200">
          <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-center">
            {/* FIX: Increased width/height for Mobile Logo */}
            <div className="relative h-50 w-50">
              <Image 
                src="/logo.png" 
                alt="Logo" 
                fill
                className="object-contain" 
                priority
              />
            </div>
          </div>
        </header>
      )}

      {/* --- MAIN CONTENT --- */}
      {/* Increased top padding (pt-20) to account for larger mobile header */}
      <main className={`
        ${hideNavbar ? "pt-0" : "pt-20 md:pt-0 md:pl-72"} 
        min-h-screen transition-all duration-300
      `}>
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6 md:py-10">
          {children}
        </div>
      </main>

      {!hideNavbar && (
        <>
          {/* --- DESKTOP SIDEBAR --- */}
          <aside className="hidden md:fixed md:inset-y-0 md:left-0 md:w-72 md:flex md:flex-col md:bg-white md:border-r md:border-zinc-200">
            
            {/* Logo Area */}
            <div className="h-28 flex items-center px-8 border-b border-zinc-100/50">
               {/* FIX: Increased width/height for Desktop Logo */}
               <div className="relative w-55 h-55">
                  <Image
                    src="/logo.png"
                    alt="Logo"
                    fill
                    className="object-contain object-left"
                    priority
                  />
               </div>
            </div>

            {/* Nav Links */}
            <div className="flex-1 px-4 py-8 space-y-8 overflow-y-auto">
              
              {/* Section 1 */}
              <div>
                <h3 className="px-4 text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-3">
                  Menu
                </h3>
                <nav className="flex flex-col gap-1.5">
                  <SidebarLink 
                    href="/feed" 
                    active={isActive("/feed")} 
                    label="Feed"
                    icon={
                      <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                    }
                  />
                  <SidebarLink 
                    href="/search" 
                    active={isActive("/search")} 
                    label="Search"
                    icon={
                      <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                    }
                  />
                  <SidebarLink 
                    href="/profile" 
                    active={isActive("/profile")} 
                    label="Profile"
                    icon={
                      <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                    }
                  />
                </nav>
              </div>

              {/* Section 2 */}
              <div>
                <h3 className="px-4 text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-3">
                  Account
                </h3>
                <nav className="flex flex-col gap-1.5">
                   <SidebarLink 
                    href="/settings" 
                    active={isActive("/settings")} 
                    label="Settings"
                    // Standard Cog Icon
                    icon={
                       <path strokeLinecap="round" strokeLinejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
                    }
                    extraIcon={
                      <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    }
                  />
                </nav>
              </div>
            </div>

            {/* Footer */}
            <div className="p-6 border-t border-zinc-100">
               <div className="text-xs text-zinc-400 font-medium">
                 &copy; 2025 SocialHouse
               </div>
            </div>
          </aside>

          {/* --- MOBILE BOTTOM NAV --- */}
          <nav className="fixed bottom-0 left-0 right-0 bg-white/95 backdrop-blur-lg border-t border-zinc-200 flex justify-between px-6 py-3 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.02)] md:hidden z-50 safe-area-bottom">
            <MobileNavLink 
              href="/feed" 
              active={isActive("/feed")} 
              label="Feed"
              icon={
                <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
              }
            />
            <MobileNavLink 
              href="/search" 
              active={isActive("/search")} 
              label="Search"
              icon={
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
              }
            />
            <MobileNavLink 
              href="/profile" 
              active={isActive("/profile")} 
              label="Profile"
              icon={
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
              }
            />
            {/* FIX: Corrected Centered Gear Icon for Mobile */}
            <MobileNavLink 
              href="/settings" 
              active={isActive("/settings")} 
              label="Settings"
              icon={
                 <>
                   <path strokeLinecap="round" strokeLinejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                   <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                 </>
              }
            />
          </nav>
        </>
      )}
    </div>
  );
}

// --- FIX: Typed Props to remove 'any' error ---
function SidebarLink({ href, active, label, icon, extraIcon }: NavLinkProps) {
  return (
    <Link
      href={href}
      className={`group flex items-center gap-3.5 px-4 py-3 rounded-xl transition-all duration-200
        ${active 
          ? "bg-blue-50 text-blue-600 shadow-sm" 
          : "text-zinc-600 hover:bg-zinc-50 hover:text-zinc-900"
        }`}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth={2}
        stroke="currentColor"
        className={`w-5 h-5 transition-colors ${active ? "text-blue-600" : "text-zinc-400 group-hover:text-zinc-600"}`}
      >
        {icon}
        {extraIcon}
      </svg>
      <span className="font-semibold text-sm">{label}</span>
    </Link>
  );
}

// --- FIX: Typed Props to remove 'any' error ---
function MobileNavLink({ href, active, label, icon }: NavLinkProps) {
  return (
    <Link
      href={href}
      className={`flex flex-col items-center justify-center w-full gap-1 transition-all duration-200
        ${active ? "text-blue-600" : "text-zinc-400 active:text-zinc-600"}`}
    >
      <div className={`p-1.5 rounded-full transition-all ${active ? "bg-blue-50" : "bg-transparent"}`}>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={active ? 2.5 : 2}
          stroke="currentColor"
          className="w-6 h-6"
        >
          {icon}
        </svg>
      </div>
      <span className="text-[10px] font-medium tracking-wide">{label}</span>
    </Link>
  );
}